name: Publish VSCode Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Bump version (no git tag/commit)
        run: |
          npm version patch --no-git-tag-version

      - name: Set Git user (for versioning)
        run: |
          git config user.name ${{ secrets.USER_NAME }}
          git config user.email ${{ secrets.USER_EMAIL }}

      - name: Compile TypeScript
        run: npm run compile

      - name: Publish
        run: |
          npx vsce publish patch -p ${{ secrets.VSCE_TOKEN }}
