name: Publish VSCode Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Bump version and generate changelog
        run: |
          npm install -g standard-version
          standard-version
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push --follow-tags origin main

      - name: Extract latest tag
        id: get_tag
        run: |
          echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Compile TypeScript
        run: npm run compile

      - name: Package Extension
        run: npx vsce package

      - name: Publish to VSCode Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v3
        with:
          name: accessibilityfixer-extension
          path: "*.vsix"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
          name: Release ${{ steps.get_tag.outputs.TAG_NAME }}
          body_path: CHANGELOG.md
