name: Publish VSCode Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Bump version (patch) and commit
        run: |
          npm install -g standard-version
          standard-version --release-as patch
          git push --follow-tags origin main

      - name: Compile TypeScript
        run: npm run compile

      - name: Set Git user (for versioning)
        run: |
          git config user.name ${{ secrets.USER_NAME }}
          git config user.email ${{ secrets.USER_EMAIL }}

      - name: Publish with Patch Version Bump
        run: |
          npx vsce publish patch -p ${{ secrets.VSCE_TOKEN }}
